before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: lLY8SlFatQq1OEW8GYjJ6EvL7V1cgMq6DeCxbSPyG5WjNqIbQpYq/ajNFWLHt6OpLqcGWY8lVJjZDfCkZqDHkG8LyK/y0foU0vIuBa7Q/1PXC2YibG+kKKSdgNZ0knompBmn2C5PXEzMQKOLug7mm5Aue9omkMOn4m9CH7HllMKkjPGznbSFJUB4mugw11MYte8xy6pvhFrQLisAIRsmbbyj9FpEJM9MIZatzZETQXC8QYPjL2NQlrzdAxun7fBnVoexDsnr4WNT6m0HnT8OR56Lefk3EuO0lrZcluzEc4k5X7cle3B/c9WIU+26bg1tJv9Mko3xjRfwAAi0E4E7/9K/C1d826ZHmg8r4g+GIiq6Z3W8488MVH4QsvcYAC0QNGvNgEl8JPwmAjIrENYGadfcwbIK+rFGToh7rg5IuWKhB9YTuH5Wz/8rpd2aSpxDlt5KSbPI/0CJNb4kqDiZprZgZUYGfVfi4LoIcj+L6bh+3LHzi2EehYWqEeeCeud6lm9/v4cio9TFbJ8H54jOjdY6KzqHb6g6vane8TjMd6s9gf50fgaHfi569hPuP/FyZnpfn8/7bBnfhqmygQmA+r5wVICRGOk7/PgIZLFDjtW5a5e9jUbOhKf/7jTt4EbW8v4NGimnIhjWj5tomIuijgsvFuMBKpUd2tv/omb2gPo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
